from turtle import *
import time
import random
setup()
bgcolor('Red')
title('3rd _____')
Reich = Turtle()
Reich.width(15)
Reich.up()
Reich.goto(0,-170)
Reich.down()
Reich.begin_fill()
Reich.circle(170)
Reich.color('White')
Reich.end_fill()
Reich.up()
Reich.goto(0,0)
Reich.down()
Reich.color('Black')
Reich.left(45)
for i in range(4):
    Reich.forward(100)
    Reich.left(90)
    Reich.forward(100)
    Reich.back(100)
    Reich.right(90)
    Reich.back(100)
    Reich.left(90)
while True:
    bgcolor('Red')
    bgcolor('Orange')
    bgcolor('Yellow')
    bgcolor('Green')
    bgcolor('Blue')
    bgcolor('Purple')
